name: lipids
channels:
  - conda-forge
dependencies:
  - sklearn-optimize
  - ase=3.19.0
  - cycler=0.10.0
  - dscribe=0.4.1 # 0.3.5 available for linux
  - ipykernel
  - ipython
  - ipywidgets
  - joblib=0.14.1
  - jupyterlab
  - matplotlib=3.2.0 # 3.2.1 available
  - mdanalysis=0.20.1
  - mypy=0.770
  - numpy=1.19.1
  - pandas=1.0.1
  - pip
  - pybind11=2.4.3 # 2.5.0 available
  - pyemd=0.5.1
  - pylint=2.4.4
  - pytest=5.4.1
  - pytest-runner=5.2
  - python=3.7.6
  - python-dateutil=2.8.1
  - scikit-learn=0.22.2.post1
  - scipy=1.4.1
  - seaborn=0.10.0
  - setuptools
  - toml=0.10.0
  - wheel
  - pip:
      - fst-pso==1.7.10
