version: 2.1

jobs:
  build:
    docker:
      - image: softmaxltd/lipids-comparison-base:base
    steps:
      - checkout
      - run:
          name: Run Tests
          command: |
            pytest scripts/tools/tests/
