version: 2.1

jobs:
  build:
    docker:
      - image: softmaxltd/lipids-comparison-base
    steps:
      - checkout
      - run:
          name: Run Tests
          command: |
            pytest lipids-comparison/scripts/tools/tests/
