version: 2.1

jobs:
  build:
    docker:
      - image: softmaxltd/lipids-comparison-base:0.0.1
    steps:
      - checkout
      - run:
          name: List
          command: ls
      - run:
          name: Run Tests
          command: |
            pytest lipids-comparison/scripts/tools/tests/
